### ISSUE TITLE
SECURITY VULNERABILITY: You have exposed a secret in your code

### ISSUE THREAD

**Issue by C0DK** [krashish8/lets-meet-slack-bot#8]
I was randomly browsing github and found your repo.

Your line:

https://github.com/krashish8/lets-meet-slack-bot/blob/master/app.js#L6

makes it possible to get access to whatever you have. You should probably fix that. I can recommend adding linting/ci/bots that check for secrets, so you won't get issues like this in the future. For more serious projects, it's a pretty huge vulnerability. 

Have a nice day!

**Comment by nishantwrp** [comment]
Thank you for pointing that out. It's a test token actually and there's no data in the server. (I'm not even sure if the server is up).
